export const GET_MODAL_STATUS = 'GET_MODAL_STATUS';
export const SET_MODAL_STATUS = 'SET_MODAL_STATUS';

export const ADD_NEW_USER = 'ADD_NEW_USER';
export const FETCH_ALL_USERS = 'FETCH_ALL_USERS';
export const FETCH_RECENT_USERS = 'FETCH_RECENT_USERS';

export const FETCH_ALL_PRODUCTS = 'FETCH_ALL_PRODUCTS';
export const FETCH_RECENT_PRODUCTS = 'FETCH_RECENT_PRODUCTS';

export const ADD_NEW_CATEGORY = 'ADD_NEW_CATEGORY';
export const FETCH_ALL_CATEGORIES = 'FETCH_ALL_CATEGORIES';
export const FETCH_RECENT_CATEGORIES = 'FETCH_RECENT_CATEGORIES';
export const FETCH_IND_CATEGORY = 'FETCH_IND_CATEGORY';