export const FETCH_ALL_USERS = 'FETCH_ALL_USERS';
export const FETCH_ALL_PRODUCTS = 'FETCH_ALL_PRODUCTS';
export const FETCH_ALL_CATEGORIES = 'FETCH_ALL_CATEGORIES';
export const ADD_NEW_CATEGORY = 'ADD_NEW_CATEGORY';